### Numpy : package from Multdimensional

In [3]:
import numpy as np

In [4]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [11]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
np.ones((2,5,int))
np

TypeError: 'type' object cannot be interpreted as an integer

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [31]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [32]:
np.random.rand(3,5)

array([[0.58727875, 0.04963089, 0.71393868, 0.3272067 , 0.70002543],
       [0.24983528, 0.21570081, 0.71040359, 0.84265383, 0.29117376],
       [0.96957279, 0.65509047, 0.78412404, 0.97610676, 0.30319094]])

In [34]:
arr=np.random.randn(2,4)
arr

array([[-0.35033182, -0.9261226 , -2.1527273 ,  0.69389402],
       [ 0.15782544, -0.28769621,  0.54814399,  0.76292588]])

In [43]:
np.random.randint(2,100)

36

In [37]:
np.random.randint(20,56,100)

array([44, 43, 36, 32, 53, 38, 45, 42, 34, 44, 22, 24, 38, 23, 53, 43, 25,
       50, 40, 33, 35, 41, 51, 52, 20, 55, 26, 34, 45, 36, 44, 55, 51, 32,
       25, 41, 29, 48, 27, 34, 45, 52, 45, 36, 46, 42, 54, 26, 31, 53, 51,
       31, 46, 36, 33, 29, 53, 22, 39, 33, 24, 38, 49, 42, 43, 20, 29, 49,
       36, 24, 38, 36, 48, 25, 49, 34, 28, 55, 54, 24, 31, 24, 36, 30, 41,
       31, 26, 50, 47, 49, 27, 55, 47, 50, 33, 53, 54, 42, 49, 27])

In [40]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
rand_array=np.random.randint(0,10,50)
rand_array

array([7, 9, 8, 1, 5, 6, 5, 1, 5, 6, 8, 9, 6, 9, 8, 3, 5, 7, 9, 3, 7, 3,
       5, 3, 1, 7, 1, 5, 9, 3, 3, 7, 3, 9, 4, 3, 2, 9, 7, 2, 8, 1, 9, 6,
       8, 6, 4, 7, 0, 6])

In [46]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (3,4)

In [52]:
rand_array.max()

9

In [54]:
rand_array.argmax()

1

In [55]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
a. T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
a=np.random.rand(2,3)
a

array([[0.76041207, 0.84944303, 0.30296391],
       [0.70911507, 0.67274472, 0.99324008]])

In [60]:
a.T

array([[0.76041207, 0.70911507],
       [0.84944303, 0.67274472],
       [0.30296391, 0.99324008]])

In [61]:
sample_array=np.arange(10.21)

sample_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
sample_array[0]

0.0

In [64]:
sample_array[2:5]

array([2., 3., 4.])

sample_array[1:4]=100
sample_array

In [69]:
|sample_array[1:4]=100
 sample_array

SyntaxError: invalid syntax (3523984122.py, line 1)

In [70]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [73]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [75]:
subset_sample_array[:]=101
subset_sample_array

array([101, 101, 101, 101, 101, 101, 101])